# =============================================================================
# Landing Zone Subscription Placement - Portal Admin Prod (REFACTORED EXAMPLE)
# This demonstrates using the landing-zone-workload module
# Deploy this AFTER alz-foundation
# =============================================================================

terraform {
  required_version = ">= 1.12.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
  backend "azurerm" {
    # Backend configuration will be provided via backend config file
    # Generated by 00-bootstrap/outputs.tf
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

# =============================================================================
# Landing Zone Workload Module
# Handles: Management group association, naming, monitoring
# =============================================================================

module "landing_zone" {
  source = "../../../shared-modules/pattern-modules/landing-zone-workload"

  # Subscription Configuration
  subscription_id       = var.subscription_id
  management_group_name = var.management_group_name

  # Landing Zone Metadata
  landing_zone_name = "portals-admin-prod"
  purpose           = "Landing Zone - Portal Admin Prod"
  environment       = var.environment
  location          = var.location
  naming_suffix     = ["portals", var.environment]

  # Monitoring
  create_log_analytics = var.create_log_analytics
  log_retention_days   = var.log_retention_days

  # Tags
  tags        = var.tags
  common_tags = var.common_tags
}
