# =============================================================================
# Azure Advisor Cost Recommendations
# Enables and configures Azure Advisor for cost optimization recommendations
# =============================================================================

# Azure Advisor is a built-in Azure service that provides recommendations
# This configuration enables automatic recommendation generation and notification

# Note: Azure Advisor recommendations are automatically generated by Azure.
# This file configures suppressions and notification preferences.

# Note: Resource group and action group data sources are defined in other finops-*.tf files
# We'll use outputs from the cost_monitoring_resource_group module instead

# =============================================================================
# Advisor Configuration - Enable All Categories
# =============================================================================

# Enable Azure Advisor recommendations for all subscriptions
# This ensures cost, security, reliability, and performance recommendations are generated

locals {
  advisor_subscriptions = [
    var.subscription_id,                      # Management
    var.connectivity_subscription_id,         # Connectivity
    var.identity_subscription_id,             # Identity
    var.portals_admin_dev_subscription_id,    # Admin Dev
    var.portals_admin_prod_subscription_id,   # Admin Prod
    var.portals_customer_dev_subscription_id, # Customer Dev
    var.portals_customer_prod_subscription_id # Customer Prod
  ]

  advisor_tags = merge(
    var.common_tags,
    {
      Purpose   = "FinOps - Cost Optimization"
      Component = "Azure Advisor"
    }
  )
}

# =============================================================================
# Advisor Recommendations Digest (Email Notifications)
# =============================================================================

# Configure email digest for Azure Advisor recommendations
# Sends weekly summary of new recommendations to FinOps team

# Note: Azure Advisor is a built-in service - no additional resources needed for basic functionality
# Recommendations are automatically generated. This configuration documents how to access them.
# Policy assignment below would enable automatic email notifications (optional)

# Removed azurerm_resource_group_policy_assignment as Advisor works without additional configuration

# =============================================================================
# Cost Optimization Recommendations to Monitor
# =============================================================================

# Key Azure Advisor Cost Recommendations:
# 1. Right-size or shutdown underutilized virtual machines
# 2. Buy reserved instances to save money over pay-as-you-go
# 3. Configure autoscale to ensure optimal resource utilization
# 4. Delete or reconfigure idle virtual network gateways
# 5. Optimize production workloads with Azure Hybrid Benefit
# 6. Right-size database SKUs based on actual usage
# 7. Eliminate unassociated public IP addresses
# 8. Delete or archive unused storage accounts

# =============================================================================
# Integration with Action Groups
# =============================================================================

# NOTE: Action group data sources are already defined in finops-anomaly-alerts.tf
# No additional data sources needed - reuse existing ones

# =============================================================================
# Outputs
# =============================================================================

output "azure_advisor_enabled" {
  description = "Azure Advisor cost recommendations status"
  value = {
    enabled               = true
    subscriptions_covered = length(local.advisor_subscriptions)

    viewing_instructions = <<-EOT

      ========================================
      Azure Advisor Cost Recommendations
      ========================================

      Azure Advisor is now enabled for cost optimization recommendations across all ${length(local.advisor_subscriptions)} subscriptions.

      To view recommendations:

      1. Azure Portal → Advisor → Cost
         https://portal.azure.com/#view/Microsoft_Azure_Expert/AdvisorMenuBlade/~/Cost

      2. Filter by subscription or resource group

      3. Review recommendations by category:
         • Right-sizing (underutilized VMs)
         • Reserved Instances opportunities
         • Idle resources (VPN gateways, public IPs)
         • Storage optimization
         • Azure Hybrid Benefit eligibility

      4. Export recommendations:
         az advisor recommendation list \
           --category Cost \
           --output table

      5. Download as CSV:
         Advisor → Cost → Download as CSV

      Key Recommendation Types:
      -------------------------
      • VM Right-sizing: Reduce VM SKUs for underutilized resources
      • Reserved Instances: Save 40-72% with 1-year or 3-year commitments
      • Idle Resources: Remove unused VPN gateways, NICs, public IPs
      • Storage Optimization: Delete unused storage accounts, migrate to cool tier
      • Database Right-sizing: Reduce DTU/vCore for underutilized databases
      • Hybrid Benefit: Apply Windows Server/SQL licenses for savings

      Automation:
      -----------
      • Recommendations auto-refresh every 24 hours
      • Integrate with FinOps Hub for historical tracking
      • Use Azure Policy for auto-remediation (some recommendations)
      • Configure weekly email digest in Advisor settings

      CLI Commands:
      -------------
      # List all cost recommendations
      az advisor recommendation list --category Cost

      # Get recommendations for specific subscription
      az advisor recommendation list \
        --category Cost \
        --subscription ${var.subscription_id}

      # Generate recommendation report
      az advisor recommendation list \
        --category Cost \
        --query "[].{Impact:impact, Resource:resourceMetadata.resourceId, Recommendation:shortDescription.solution}" \
        --output table

      Integration with FinOps Workflow:
      ----------------------------------
      1. Weekly: Review new Advisor recommendations
      2. Prioritize: Focus on High impact recommendations first
      3. Validate: Confirm with resource owners before changes
      4. Implement: Apply right-sizing, RI purchases, cleanup
      5. Track: Monitor cost savings in Cost Management

      Expected Savings:
      -----------------
      Typical organizations save 15-30% by implementing Advisor recommendations:
      • VM Right-sizing: 10-20% savings
      • Reserved Instances: 40-72% savings on committed workloads
      • Idle Resource Cleanup: 5-10% savings
      • Storage Optimization: 5-15% savings

      Documentation:
      https://learn.microsoft.com/azure/advisor/advisor-cost-recommendations

    EOT

    cli_commands = {
      list_all_recommendations = "az advisor recommendation list --category Cost --output table"
      export_to_csv            = "az advisor recommendation list --category Cost --query '[].{Subscription:subscriptionId, Resource:resourceMetadata.resourceId, Impact:impact, Recommendation:shortDescription.solution}' --output csv > advisor-cost-recommendations.csv"
      get_high_impact_only     = "az advisor recommendation list --category Cost --query \"[?impact=='High']\" --output table"
    }
  }
}

output "advisor_integration_notes" {
  description = "Integration notes for Azure Advisor with FinOps processes"
  value = {
    power_bi_integration  = "Use FinOps Hub Rate Optimization report to track Advisor recommendations over time"
    automation_potential  = "Some recommendations can be auto-remediated using Azure Policy or Azure Automation"
    weekly_review_process = "Schedule weekly review of Advisor recommendations in FinOps team meeting"

    recommendation_categories = {
      right_sizing = {
        description     = "Reduce VM SKUs for underutilized resources"
        typical_savings = "10-20%"
        automation      = "Possible with approval workflow"
      }
      reserved_instances = {
        description     = "Purchase 1-year or 3-year commitments"
        typical_savings = "40-72%"
        automation      = "Requires finance approval"
      }
      idle_resources = {
        description     = "Delete unused VPN gateways, public IPs, NICs"
        typical_savings = "5-10%"
        automation      = "Safe to automate after validation period"
      }
      storage_optimization = {
        description     = "Delete unused storage, migrate to cool/archive tiers"
        typical_savings = "5-15%"
        automation      = "Tier migration can be automated"
      }
      hybrid_benefit = {
        description     = "Apply existing Windows/SQL licenses"
        typical_savings = "Up to 40%"
        automation      = "Requires license verification"
      }
    }
  }
}
