# =============================================================================
# Landing Zone Subscription Placement - Connectivity
# This places the connectivity subscription into the acme-connectivity management group
# Deploy this AFTER alz-foundation
# =============================================================================

terraform {
  required_version = ">= 1.12.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
  backend "azurerm" {
    # Backend configuration will be provided via backend config file
    # Generated by 00-bootstrap/outputs.tf
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

# Data source to get the acme-connectivity management group
data "azurerm_management_group" "connectivity" {
  name = var.management_group_name
}

# Place the connectivity subscription into the acme-connectivity management group
resource "azurerm_management_group_subscription_association" "connectivity" {
  management_group_id = data.azurerm_management_group.connectivity.id
  subscription_id     = "/subscriptions/${var.subscription_id}"
}

# =============================================================================
# Naming Module for Consistent Azure Resource Naming
# =============================================================================

module "naming" {
  source   = "../../shared-modules/naming"
  location = var.location
  suffix   = ["connectivity", "prod"]
}

# Prepare common tags for all resources
locals {
  common_tags = merge(
    var.tags,
    {
      Purpose         = "Landing Zone - Connectivity"
      LandingZone     = "connectivity"
      Environment     = "production"
      ManagementGroup = var.management_group_name
      ManagedBy       = "Terraform"
      DeployedBy      = "AVM"
    }
  )
}
