# =============================================================================
# Landing Zone Subscription Placement - Management
# This places the management subscription into the acme-management management group
# Deploy this AFTER alz-foundation
# =============================================================================

terraform {
  required_version = ">= 1.12.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
  backend "azurerm" {
    # Backend configuration will be provided via backend config file
    # Generated by 00-bootstrap/outputs.tf
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

# Data source to get the acme-management management group
data "azurerm_management_group" "management" {
  name = var.management_group_name
}

# Place the management subscription into the acme-management management group
resource "azurerm_management_group_subscription_association" "management" {
  management_group_id = data.azurerm_management_group.management.id
  subscription_id     = "/subscriptions/${var.subscription_id}"
}
